#!/bin/bash

set -e

# Get the URL of the Loki instance.
LOKI_URL=${LOKI_URL:-"http://localhost:81/loki/api/v1/push"}

case "$1" in
  loki:install)
    # Install the loki-docker-driver if not installed.
    if ! docker plugin ls | grep loki; then
      docker plugin install grafana/loki-docker-driver:latest --alias loki
    fi
    ;;

  loki:link)
    APP="$2"
    if [ -z "$APP" ]; then
      echo "Error: App name must be provided."
      exit 1
    fi

    # Set Docker options for the app to use the Loki logging driver.
    dokku docker-options:add "$APP" run "--log-driver=loki --log-opt loki-url=$LOKI_URL"

    echo "Docker options for app $APP updated to use Loki. Please redeploy your app for changes to take effect."

    ;;

  *)
    # If no commands match, do nothing.
    ;;
esac
